### ISSUE TITLE
SyntaxError: Unexpected reserved word: "await"

### ISSUE THREAD

**Issue by tdmarchetta** [Neztore/tls-rpt-monitor#5]
```Shell
tdmarchetta@yellowfish:~/docker/tls-rpt-monitor/tls-rpt-monitor$ npm start

> tls-rpt-monitor@1.1.0 start
> node index.mjs

file:///home/tdmarchetta/docker/tls-rpt-monitor/tls-rpt-monitor/config.mjs:6
  const contents = await readFile(filePath, {encoding: 'utf8'});
                   ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
```

I do apologize if this is an easy solution. I am just not able to figure this out. I do appreciate any assistance.

**Comment by Neztore** [comment]
Hi there,

What is your node version? (`node -v`) - config.mjs uses of [top-level await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#browser_compatibility) which requires Node.js version v14.8.0 or newer.

**Comment by tdmarchetta** [comment]
Hi @Neztore 

`v12.22.9`

**Comment by tdmarchetta** [comment]
@Neztore Thank you for your help. I was able to get it up and running. Now I just have to figure out how to point the MTA-STA to HTTPS.
<img width="371" alt="image" src="https://github.com/Neztore/tls-rpt-monitor/assets/13514333/8ff5119b-933e-47ac-ba55-39db6cd0dc18">

I'm making some assumptions that you expect there to be a web proxy on the front of this web service. Right?

**Comment by Neztore** [comment]
It should be used with a proxy - Nginx for example can handle https with letsencrypt and proxy to the application server via. http. The RFC (and mechanism by which MTA-STS provides protection) requires HTTPS to be used.

You could modify the code to add https support directly, but it is not currently supported (please feel free to open a PR if desired). A reverse proxy would also provide functionality such as caching, ratelimiting. 

The page you have sent is returned when requests are made to the index. POST requests are received on the path `/v1/tls-rpt`.

An example record is:
```
_smtp._tls v=TLSRPTv1;rua=https://example.com/v1/tls-rpt
```

**Comment by tdmarchetta** [comment]
@Neztore Thank you for taking the time to build this. This is a very useful.
I think the only thing I don't understand. is the configurations for the smtp settings What file do you enter those into?

Once I have this up and running and in production. I would like to help out any way I can with this project. Would you be open to letting me help with documentation?

**Comment by Neztore** [comment]
Please see below from the README.md. SMTP settings should be set as an environment variable. You can do this via. your process manager (such as pm2) or if you are using Docker, in your Dockerfile. These are environment variables and not in config.json for security reasons.

Please feel free to contribute to documentation - Pull requests are welcome.

![image](https://github.com/Neztore/tls-rpt-monitor/assets/25391241/a38b06be-caab-4f5a-983f-170485bf1218)

**Comment by tdmarchetta** [comment]
@Neztore Okay, I will puzzle this together and figure this out little by little. 
Is this service capable of handling multiple domains, or is it limited to handling a single domain?

**Comment by Neztore** [comment]
It can handle many domains - the Express application code makes no use of Host information, so you can use a proxy to point any domain at it.
The [section at the end of the readme](https://github.com/Neztore/tls-rpt-monitor/tree/main?tab=readme-ov-file#setting-up-recipients) describes how to configure it to handle multiple domains. Personally, I use the same domain and URL for all of my domains - and use an "otherwise" to send all of the emails to the same place.

**Comment by Neztore** [comment]
Closing this issue as completed. Let me know if you have any other issues.
