### ISSUE TITLE
Reporting server

### ISSUE THREAD

**Issue by Blason** [Neztore/tls-rpt-monitor#8]
Does that mean it starts web server on port 80 or port 443 and accepts a request?

**Comment by Neztore** [comment]
By default, it runs on port 3000.
https://github.com/Neztore/tls-rpt-monitor/blob/6edd1941ad69f7c77cf13ec01e13bcba0e35394b/index.mjs#L13

You can change the port by specifying the `port` environment. The project doesn't currently support handling https (and https is required by the specification), so you need to put a reverse proxy in-front of it.

Please feel free to open a pull request if you would like to add direct https support.
